name: Update gist with WakaTime stats
on:
  schedule:
    - cron: "0 * * * *"
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Update gist
        uses: matchai/waka-box@master
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: cc9c25e5767354a3ff7f5fa0b0db75b8
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
